import psycopg2
import os

# Load .env file
if os.path.exists('.env'):
    with open('.env') as f:
        for line in f:
            if '=' in line and not line.startswith('#'):
                k, v = line.strip().split('=', 1)
                os.environ[k] = v

dsn = os.environ.get("DATABASE_URL")
if not dsn:
    print("No DATABASE_URL found in .env")
    exit(1)

conn = psycopg2.connect(dsn=dsn)
cur = conn.cursor()

sample_vehicles = [
    {
        "vehicle_number": "TS09EA1234",
        "letzryd_unique_no": "LZ-HYD-001",
        "city_name": "Hyderabad",
        "model": "Tata Nexon EV",
        "fuel_type": "Electric",
        "received_allocated": "PDI Done",
        "delivery_month": "2024-03",
        "registration_date": "2024-01-15",
        "rto_tax_validity": "2029-01-14",
        "permit_validity": "2029-01-14",
        "fitness_validity": "2026-01-14",
        "pollution_validity": "2025-01-14",
        "insurance_validity": "2025-01-14",
        "insurance_broker": "PolicyBazaar",
        "insurance_underwriter": "ICICI Lombard",
        "insurance_start_date": "2024-01-15",
        "kms_reading": 12450,
        "tracking_device_vendor": "Roadcast",
        "tracking_device_type": "AIS140",
        "cng_installed": "No",
        "cng_plate": "",
        "cng_installation_date": None,
        "jack": "Available",
        "jack_rod": "Available",
        "spanner": "Available",
        "parking_triangle": "Available",
        "fire_extinguishers": "Available",
        "seat_cover": "Available",
        "floor_carpet": "Available",
        "key_quantity": 2
    },
    {
        "vehicle_number": "KA01MJ5678",
        "letzryd_unique_no": "LZ-BLR-002",
        "city_name": "Bangalore",
        "model": "Maruti WagonR CNG",
        "fuel_type": "CNG",
        "received_allocated": "In Process",
        "delivery_month": "2024-04",
        "registration_date": "2024-02-10",
        "rto_tax_validity": "2029-02-09",
        "permit_validity": "2029-02-09",
        "fitness_validity": "2026-02-09",
        "pollution_validity": "2025-02-09",
        "insurance_validity": "2025-02-09",
        "insurance_broker": "Coverfox",
        "insurance_underwriter": "Bajaj Allianz",
        "insurance_start_date": "2024-02-10",
        "kms_reading": 8900,
        "tracking_device_vendor": "LocoNav",
        "tracking_device_type": "OBD-II",
        "cng_installed": "Yes",
        "cng_plate": "CNG-KA-9921",
        "cng_installation_date": "2024-02-05",
        "jack": "Available",
        "jack_rod": "Available",
        "spanner": "Available",
        "parking_triangle": "Available",
        "fire_extinguishers": "Available",
        "seat_cover": "Available",
        "floor_carpet": "Available",
        "key_quantity": 2
    },
    {
        "vehicle_number": "MH02CK9101",
        "letzryd_unique_no": "LZ-MUM-003",
        "city_name": "Mumbai",
        "model": "Hyundai Aura CNG",
        "fuel_type": "CNG",
        "received_allocated": "Ready for Delivery",
        "delivery_month": "2024-01",
        "registration_date": "2023-11-20",
        "rto_tax_validity": "2028-11-19",
        "permit_validity": "2028-11-19",
        "fitness_validity": "2025-11-19",
        "pollution_validity": "2024-11-19",
        "insurance_validity": "2024-11-19",
        "insurance_broker": "PolicyBazaar",
        "insurance_underwriter": "HDFC ERGO",
        "insurance_start_date": "2023-11-20",
        "kms_reading": 22100,
        "tracking_device_vendor": "AutoGrade",
        "tracking_device_type": "GPS-4G",
        "cng_installed": "Yes",
        "cng_plate": "CNG-MH-4412",
        "cng_installation_date": "2023-11-15",
        "jack": "Available",
        "jack_rod": "Available",
        "spanner": "Available",
        "parking_triangle": "Available",
        "fire_extinguishers": "Available",
        "seat_cover": "Available",
        "floor_carpet": "Available",
        "key_quantity": 2
    },
    {
        "vehicle_number": "TN07BP3344",
        "letzryd_unique_no": "LZ-CHE-004",
        "city_name": "Chennai",
        "model": "Tata Tigor EV",
        "fuel_type": "Electric",
        "received_allocated": "PDI Done",
        "delivery_month": "2024-05",
        "registration_date": "2024-03-01",
        "rto_tax_validity": "2029-02-28",
        "permit_validity": "2029-02-28",
        "fitness_validity": "2026-02-28",
        "pollution_validity": "2025-02-28",
        "insurance_validity": "2025-02-28",
        "insurance_broker": "PolicyBazaar",
        "insurance_underwriter": "Tata AIG",
        "insurance_start_date": "2024-03-01",
        "kms_reading": 4500,
        "tracking_device_vendor": "Roadcast",
        "tracking_device_type": "AIS140",
        "cng_installed": "No",
        "cng_plate": "",
        "cng_installation_date": None,
        "jack": "Available",
        "jack_rod": "Available",
        "spanner": "Available",
        "parking_triangle": "Available",
        "fire_extinguishers": "Available",
        "seat_cover": "Available",
        "floor_carpet": "Available",
        "key_quantity": 2
    },
    {
        "vehicle_number": "DL01CZ8899",
        "letzryd_unique_no": "LZ-DEL-005",
        "city_name": "Delhi",
        "model": "Mahindra XUV400 EV",
        "fuel_type": "Electric",
        "received_allocated": "In Process",
        "delivery_month": "2024-06",
        "registration_date": "2024-04-12",
        "rto_tax_validity": "2029-04-11",
        "permit_validity": "2029-04-11",
        "fitness_validity": "2026-04-11",
        "pollution_validity": "2025-04-11",
        "insurance_validity": "2025-04-11",
        "insurance_broker": "Ackodrive",
        "insurance_underwriter": "Acko General",
        "insurance_start_date": "2024-04-12",
        "kms_reading": 3200,
        "tracking_device_vendor": "LocoNav",
        "tracking_device_type": "OBD-II",
        "cng_installed": "No",
        "cng_plate": "",
        "cng_installation_date": None,
        "jack": "Available",
        "jack_rod": "Available",
        "spanner": "Available",
        "parking_triangle": "Available",
        "fire_extinguishers": "Available",
        "seat_cover": "Available",
        "floor_carpet": "Available",
        "key_quantity": 2
    },
    {
        "vehicle_number": "TS10EB5566",
        "letzryd_unique_no": "LZ-HYD-006",
        "city_name": "Hyderabad",
        "model": "Maruti Tour S CNG",
        "fuel_type": "CNG",
        "received_allocated": "PDI Done",
        "delivery_month": "2024-02",
        "registration_date": "2023-12-18",
        "rto_tax_validity": "2028-12-17",
        "permit_validity": "2028-12-17",
        "fitness_validity": "2025-12-17",
        "pollution_validity": "2024-12-17",
        "insurance_validity": "2024-12-17",
        "insurance_broker": "PolicyBazaar",
        "insurance_underwriter": "SBI General",
        "insurance_start_date": "2023-12-18",
        "kms_reading": 18900,
        "tracking_device_vendor": "Roadcast",
        "tracking_device_type": "AIS140",
        "cng_installed": "Yes",
        "cng_plate": "CNG-TS-8820",
        "cng_installation_date": "2023-12-10",
        "jack": "Available",
        "jack_rod": "Available",
        "spanner": "Available",
        "parking_triangle": "Available",
        "fire_extinguishers": "Available",
        "seat_cover": "Available",
        "floor_carpet": "Available",
        "key_quantity": 2
    },
    {
        "vehicle_number": "KA03ND7788",
        "letzryd_unique_no": "LZ-BLR-007",
        "city_name": "Bangalore",
        "model": "Tata Express-T EV",
        "fuel_type": "Electric",
        "received_allocated": "Ready for Delivery",
        "delivery_month": "2024-01",
        "registration_date": "2023-10-05",
        "rto_tax_validity": "2028-10-04",
        "permit_validity": "2028-10-04",
        "fitness_validity": "2025-10-04",
        "pollution_validity": "2024-10-04",
        "insurance_validity": "2024-10-04",
        "insurance_broker": "PolicyBazaar",
        "insurance_underwriter": "Royal Sundaram",
        "insurance_start_date": "2023-10-05",
        "kms_reading": 29400,
        "tracking_device_vendor": "AutoGrade",
        "tracking_device_type": "GPS-4G",
        "cng_installed": "No",
        "cng_plate": "",
        "cng_installation_date": None,
        "jack": "Available",
        "jack_rod": "Available",
        "spanner": "Available",
        "parking_triangle": "Available",
        "fire_extinguishers": "Available",
        "seat_cover": "Available",
        "floor_carpet": "Available",
        "key_quantity": 2
    },
    {
        "vehicle_number": "MH04FR4455",
        "letzryd_unique_no": "LZ-MUM-008",
        "city_name": "Mumbai",
        "model": "Hyundai Xcent Prime CNG",
        "fuel_type": "CNG",
        "received_allocated": "In Process",
        "delivery_month": "2024-05",
        "registration_date": "2024-03-22",
        "rto_tax_validity": "2029-03-21",
        "permit_validity": "2029-03-21",
        "fitness_validity": "2026-03-21",
        "pollution_validity": "2025-03-21",
        "insurance_validity": "2025-03-21",
        "insurance_broker": "Coverfox",
        "insurance_underwriter": "New India Assurance",
        "insurance_start_date": "2024-03-22",
        "kms_reading": 6700,
        "tracking_device_vendor": "LocoNav",
        "tracking_device_type": "OBD-II",
        "cng_installed": "Yes",
        "cng_plate": "CNG-MH-1190",
        "cng_installation_date": "2024-03-15",
        "jack": "Available",
        "jack_rod": "Available",
        "spanner": "Available",
        "parking_triangle": "Available",
        "fire_extinguishers": "Available",
        "seat_cover": "Available",
        "floor_carpet": "Available",
        "key_quantity": 2
    },
    {
        "vehicle_number": "TS08EX1122",
        "letzryd_unique_no": "LZ-HYD-009",
        "city_name": "Hyderabad",
        "model": "Tata Nexon EV Max",
        "fuel_type": "Electric",
        "received_allocated": "Ready for Delivery",
        "delivery_month": "2024-06",
        "registration_date": "2024-04-01",
        "rto_tax_validity": "2029-03-31",
        "permit_validity": "2029-03-31",
        "fitness_validity": "2026-03-31",
        "pollution_validity": "2025-03-31",
        "insurance_validity": "2025-03-31",
        "insurance_broker": "PolicyBazaar",
        "insurance_underwriter": "ICICI Lombard",
        "insurance_start_date": "2024-04-01",
        "kms_reading": 2100,
        "tracking_device_vendor": "Roadcast",
        "tracking_device_type": "AIS140",
        "cng_installed": "No",
        "cng_plate": "",
        "cng_installation_date": None,
        "jack": "Available",
        "jack_rod": "Available",
        "spanner": "Available",
        "parking_triangle": "Available",
        "fire_extinguishers": "Available",
        "seat_cover": "Available",
        "floor_carpet": "Available",
        "key_quantity": 2
    },
    {
        "vehicle_number": "KA05MK9900",
        "letzryd_unique_no": "LZ-BLR-010",
        "city_name": "Bangalore",
        "model": "Maruti Ertiga CNG",
        "fuel_type": "CNG",
        "received_allocated": "PDI Done",
        "delivery_month": "2024-02",
        "registration_date": "2023-11-10",
        "rto_tax_validity": "2028-11-09",
        "permit_validity": "2028-11-09",
        "fitness_validity": "2025-11-09",
        "pollution_validity": "2024-11-09",
        "insurance_validity": "2024-11-09",
        "insurance_broker": "PolicyBazaar",
        "insurance_underwriter": "Tata AIG",
        "insurance_start_date": "2023-11-10",
        "kms_reading": 15400,
        "tracking_device_vendor": "AutoGrade",
        "tracking_device_type": "GPS-4G",
        "cng_installed": "Yes",
        "cng_plate": "CNG-KA-3310",
        "cng_installation_date": "2023-11-01",
        "jack": "Available",
        "jack_rod": "Available",
        "spanner": "Available",
        "parking_triangle": "Available",
        "fire_extinguishers": "Available",
        "seat_cover": "Available",
        "floor_carpet": "Available",
        "key_quantity": 2
    }
]

# Truncate and insert
cur.execute("TRUNCATE TABLE copy_vehicle_onboarding RESTART IDENTITY;")

insert_query = """
INSERT INTO copy_vehicle_onboarding (
    vehicle_number, letzryd_unique_no, city_name, model, fuel_type,
    received_allocated, delivery_month, registration_date, rto_tax_validity,
    permit_validity, fitness_validity, pollution_validity, insurance_validity,
    insurance_broker, insurance_underwriter, insurance_start_date, kms_reading,
    tracking_device_vendor, tracking_device_type, cng_installed, cng_plate,
    cng_installation_date, jack, jack_rod, spanner, parking_triangle,
    fire_extinguishers, seat_cover, floor_carpet, key_quantity
) VALUES (
    %(vehicle_number)s, %(letzryd_unique_no)s, %(city_name)s, %(model)s, %(fuel_type)s,
    %(received_allocated)s, %(delivery_month)s, %(registration_date)s, %(rto_tax_validity)s,
    %(permit_validity)s, %(fitness_validity)s, %(pollution_validity)s, %(insurance_validity)s,
    %(insurance_broker)s, %(insurance_underwriter)s, %(insurance_start_date)s, %(kms_reading)s,
    %(tracking_device_vendor)s, %(tracking_device_type)s, %(cng_installed)s, %(cng_plate)s,
    %(cng_installation_date)s, %(jack)s, %(jack_rod)s, %(spanner)s, %(parking_triangle)s,
    %(fire_extinguishers)s, %(seat_cover)s, %(floor_carpet)s, %(key_quantity)s
);
"""

for v in sample_vehicles:
    cur.execute(insert_query, v)

conn.commit()
print(f"Successfully inserted {len(sample_vehicles)} sample vehicle entries!")

cur.close()
conn.close()
