services:
  - type: web
    name: portal-web-app
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DB_HOST
        fromDatabase:
          name: portal-postgres-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: portal-postgres-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: portal-postgres-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: portal-postgres-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portal-postgres-db
          property: password
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: portal-postgres-db
    databaseName: portal_db
    user: postgres
    plan: free
    region: singapore
